### ISSUE TITLE
need your help for applying this only to gvim[fyi, it is not realted to any bug]

### ISSUE THREAD

**Issue by vadirajks** [psych3r/vim-remembers#2]
Firstly, this is awesome and i was looking for this for many days now.
I see gvim and vim are referring to same .vimrc by check :h vimrc. I wanted to apply this only to gvim and not to vim. 
If you don't mind, can you please let me know how to apply this only to gvim if possible.
Thank you for all your help and sharing your great work.

**Comment by psych3r** [comment]
@vadirajks Add those lines to your .vimrc **before loading plugins** to have vim-remembers work in gvim only and not in vim

```
if !has('gui_running') 
	let g:loaded_remembers = 1 
endif
```

Thank you for your kind words!
